### ISSUE TITLE
It won't start. Version mcpitanlib-2.0.3-1.20.1-forge. 

### ISSUE THREAD

**Issue by gri3229** [Pitan76/MCPitanLibarch#11]
When launching the launcher first starts loading, and then exits. In the folder with crash reports is not fixed. I use 1.20.1 neoforge 47.1.96. I attach debug.
[debug.log](https://github.com/Pitan76/MCPitanLibarch/files/14311687/debug.log)
On version mcpitanlib-2.0.4-1.20.1-forge it is exactly the same.

**Comment by PTOM76** [comment]
debug.log do not contain error about MCPitanLib, but it may have been fixed in MCPitanLib 2.0.5, so please check.

**Comment by gri3229** [comment]
> debug.log do not contain error about MCPitanLib, but it may have been fixed in MCPitanLib 2.0.5, so please check.
With MCPitanLib 2.0.5 everything worked, thanks.
