### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pocinhas** [Pitan76/MCPitanLibarch#4]
hey there, when updating your mod to the latest version my minecraft crashes, 1.2.8 works just fine: 
[crash-2022-12-22_23.20.51-client.txt](https://github.com/Pitan76/MCPitanLibarch/files/10290895/crash-2022-12-22_23.20.51-client.txt)

**Comment by PTOM76** [comment]
Thanks for your reporting!
Incorporated SnakeYaml and fixed a crashing bug.
