### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcpitanlibarch'!

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [Pitan76/MCPitanLibarch#6]
Error Log: https://pastebin.com/vrdvsEyX
Mods: included in error log.
Version: 1.17.1
Mod loader: Fabric

**Comment by PTOM76** [comment]
https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/3807017
did you install this in? It wasn't listed in the log.

**Comment by mrdiamondmanguydudeman** [comment]
I just downloaded it, it doesn't fix it

**Comment by mrdiamondmanguydudeman** [comment]
same error

**Comment by mrdiamondmanguydudeman** [comment]
this is new error log idk if this is new or not though, https://pastebin.com/QWrxqhBn

**Comment by PTOM76** [comment]
Looking at the error log, it seems that there is no Architecture API. Also try the latest MCPitanLib.

**Comment by mrdiamondmanguydudeman** [comment]
ok ill try

**Comment by mrdiamondmanguydudeman** [comment]
it doesn't work, same error message, got latest version and i have architectury api in there

**Comment by PTOM76** [comment]
umm, What is the error?

**Comment by mrdiamondmanguydudeman** [comment]
so i reinstalled architectury and it worked idk what happened but its fixed now

**Comment by mrdiamondmanguydudeman** [comment]
i tried it multiple times before i dont know why it works now
