### ISSUE TITLE
Latest version says not compatible

### ISSUE THREAD

**Issue by pokesmells** [Pitan76/MCPitanLibarch#7]
![image](https://user-images.githubusercontent.com/33227568/221366645-4f2ada7c-74d7-40f2-b9b7-fae1a7f83700.png)

I updated and it says it's not compatible even though the update says it's good for 1.19.2 and 1.19.3

**Comment by pokesmells** [comment]
I should note, that this update that I did, was pushed up for my game version. So I am not aware if this is correct on curseforges side.

**Comment by pokesmells** [comment]
![image](https://user-images.githubusercontent.com/33227568/221366951-f22fa4aa-b526-47e9-899d-4a1a4726aaa0.png)

**Comment by PTOM76** [comment]
Fixed CurseForge versioning.
