### ISSUE TITLE
MCPitanLibarch conflicts with the Prefab mod

### ISSUE THREAD

**Issue by Sibei46** [Pitan76/MCPitanLibarch#8]
Prefab and MCPitanLibarch are added together, resulting in no resurrection
(Machine Flip Understanding)

original：Prefab跟MCPitanLibarch加在一块导致无法复活
(机翻谅解)

**Comment by PTOM76** [comment]
Forge?Fabric?

**Comment by PTOM76** [comment]
Works fine in Fabric, but not in Forge?

**Comment by Sibei46** [comment]
Right at Fabric

**Comment by Sibei46** [comment]
It is "rebirth"

**Comment by PTOM76** [comment]
Can you provide a crash log or something?

**Comment by PTOM76** [comment]
It was the bug of Item Alchemy
